In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Reading the file

df=pd.read_csv('/content/Superstore.csv', encoding='latin1')
display(df.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')
if 'Ship Date' in df.columns:
    df['Ship Date'] = pd.to_datetime(df['Ship Date'], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [ ]:
# creating profit margin column in df
df['ProfitMargin'] = np.where(df['Sales'] == 0, np.nan, df['Profit'] / df['Sales'])
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,ProfitMargin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0.1600
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0.3000
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0.4700
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,-0.4000
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,0.1125

In [ ]:
# Average ProfitMargin per Region
avg_pm_region = df.groupby('Region')['ProfitMargin'].mean().sort_values(ascending=False)
print("\nAverage ProfitMargin by Region:")
print(avg_pm_region)

Average ProfitMargin by Region:
Region
West       0.219487
East       0.167227
South      0.163519
Central   -0.104073
Name: ProfitMargin, dtype: float64

In [ ]:
df['OrderMonth'] = df['Order Date'].dt.to_period('M').dt.to_timestamp()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  ProfitMargin   9994 non-null   float64
 22  OrderMonth     9994 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(4), int64(3), object(13)
memory usage: 1.8+ MB

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,ProfitMargin,OrderMonth
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0.1600,2016-11-01
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0.3000,2016-11-01
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0.4700,2016-06-01
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,-0.4000,2015-10-01
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,0.1125,2015-10-01

In [ ]:
# Compute total Sales per Region x Month
monthly_sales = (
    df
    .groupby(['Region', 'OrderMonth'], as_index=False)['Sales']
    .sum()
    .sort_values(['Region', 'OrderMonth'])
)
print("\nTotal Sales per Region x Month:")
print(monthly_sales)

Total Sales per Region x Month:
      Region OrderMonth      Sales
0    Central 2014-01-01   1539.906
1    Central 2014-02-01   1233.174
2    Central 2014-03-01   5827.602
3    Central 2014-04-01   3712.340
4    Central 2014-05-01   4048.506
..       ...        ...        ...
187     West 2017-08-01  25737.894
188     West 2017-09-01  27907.037
189     West 2017-10-01  21212.436
190     West 2017-11-01  28941.787
191     West 2017-12-01  29652.095

[192 rows x 3 columns]

In [ ]:
# For each region, compute previous month's total sales (shift)
monthly_sales['Sales_prev_month'] = monthly_sales.groupby('Region')['Sales'].shift(1)
monthly_sales.head()

    Region OrderMonth     Sales  Sales_prev_month
0  Central 2014-01-01  1539.906               NaN
1  Central 2014-02-01  1233.174          1539.906
2  Central 2014-03-01  5827.602          1233.174
3  Central 2014-04-01  3712.340          5827.602
4  Central 2014-05-01  4048.506          3712.340

In [ ]:
# Merge Sales_prev_month back into original df (join on Region + OrderMonth)
df = df.merge(
    monthly_sales[['Region', 'OrderMonth', 'Sales_prev_month']],
    on=['Region', 'OrderMonth'],
    how='left'
)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,ProfitMargin,OrderMonth,Sales_prev_month
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0.1600,2016-11-01,3165.234
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0.3000,2016-11-01,3165.234
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0.4700,2016-06-01,10694.247
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,-0.4000,2015-10-01,13677.487
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,0.1125,2015-10-01,13677.487

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            9994 non-null   int64
 1   Order ID          9994 non-null   object
 2   Order Date        9994 non-null   datetime64[ns]
 3   Ship Date         9994 non-null   datetime64[ns]
 4   Ship Mode         9994 non-null   object
 5   Customer ID       9994 non-null   object
 6   Customer Name     9994 non-null   object
 7   Segment           9994 non-null   object
 8   Country           9994 non-null   object
 9   City              9994 non-null   object
 10  State             9994 non-null   object
 11  Postal Code       9994 non-null   int64
 12  Region            9994 non-null   object
 13  Product ID        9994 non-null   object
 14  Category          9994 non-null   object
 15  Sub-Category      9994 non-null   object
 16  Product Name      9994 non-null   object
 17  Sales             9994 non-null   float64
 18  Quantity          9994 non-null   int64
 19  Discount          9994 non-null   float64
 20  Profit            9994 non-null   float64
 21  ProfitMargin      9994 non-null   float64
 22  OrderMonth        9994 non-null   datetime64[ns]
 23  Sales_prev_month  9915 non-null   float64
dtypes: datetime64[ns](3), float64(5), int64(3), object(13)
memory usage: 1.8+ MB

In [ ]:
# Show a few rows
print("\nExample rows with ProfitMargin and Sales_prev_month:")
print(df[['Order ID','Order Date','Region','Sales','Profit','ProfitMargin','OrderMonth','Sales_prev_month']].head(8))

Example rows with ProfitMargin and Sales_prev_month:
         Order ID Order Date Region     Sales    Profit  ProfitMargin  \
0  CA-2016-152156 2016-11-08  South  261.9600   41.9136        0.1600
1  CA-2016-152156 2016-11-08  South  731.9400  219.5820        0.3000
2  CA-2016-138688 2016-06-12   West   14.6200    6.8714        0.4700
3  US-2015-108966 2015-10-11  South  957.5775 -383.0310       -0.4000
4  US-2015-108966 2015-10-11  South   22.3680    2.5164        0.1125
5  CA-2014-115812 2014-06-09   West   48.8600   14.1694        0.2900
6  CA-2014-115812 2014-06-09   West    7.2800    1.9656        0.2700
7  CA-2014-115812 2014-06-09   West  907.1520   90.7152        0.1000

  OrderMonth  Sales_prev_month
0 2016-11-01          3165.234
1 2016-11-01          3165.234
2 2016-06-01         10694.247
3 2015-10-01         13677.487
4 2015-10-01         13677.487
5 2014-06-01          6570.438
6 2014-06-01          6570.438
7 2014-06-01          6570.438

In [ ]:
# --- 2. Encoding ---

In [ ]:
# One-hot encode Segment
if 'Segment' in df.columns:
    seg_dummies = pd.get_dummies(df['Segment'], prefix='Segment')
    df = pd.concat([df, seg_dummies], axis=1)
    print("\nOne-hot columns added:", list(seg_dummies.columns))

One-hot columns added: ['Segment_Consumer', 'Segment_Corporate', 'Segment_Home Office']

In [ ]:
# Target encode Region by mean ProfitMargin (map mean ProfitMargin per region into new column)
region_pm_mean = df.groupby('Region')['ProfitMargin'].mean()
df['Region_TargetEnc'] = df['Region'].map(region_pm_mean)

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Quantity,Discount,Profit,ProfitMargin,OrderMonth,Sales_prev_month,Segment_Consumer,Segment_Corporate,Segment_Home Office,Region_TargetEnc
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,2,0.00,41.9136,0.1600,2016-11-01,3165.234,True,False,False,0.163519
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,0.00,219.5820,0.3000,2016-11-01,3165.234,True,False,False,0.163519
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,2,0.00,6.8714,0.4700,2016-06-01,10694.247,False,True,False,0.219487
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,5,0.45,-383.0310,-0.4000,2015-10-01,13677.487,True,False,False,0.163519
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2,0.20,2.5164,0.1125,2015-10-01,13677.487,True,False,False,0.163519

In [ ]:
region_pm_mean

Region
Central   -0.104073
East       0.167227
South      0.163519
West       0.219487
Name: ProfitMargin, dtype: float64

In [ ]:
print("\nRegion -> mean ProfitMargin mapping:")
print(region_pm_mean)

Region -> mean ProfitMargin mapping:
Region
Central   -0.104073
East       0.167227
South      0.163519
West       0.219487
Name: ProfitMargin, dtype: float64

In [ ]:
# --- 3. Standardization / Scaling ---

In [ ]:
numeric_cols = ['Sales', 'Quantity', 'Discount', 'ProfitMargin']
# Confirm columns exist; create scaled columns for only existing ones
existing_numeric = [c for c in numeric_cols if c in df.columns]
existing_numeric

['Sales', 'Quantity', 'Discount', 'ProfitMargin']

In [ ]:
# Compute z-score with ddof=0 (population std); if you prefer sample std use ddof=1
for col in existing_numeric:
    mean = df[col].mean(skipna=True)
    std = df[col].std(ddof=0, skipna=True)
    if std == 0 or np.isnan(std):
        # Avoid divide by zero: produce zeros if all equal
        df[f'{col}_z'] = 0.0
    else:
        df[f'{col}_z'] = (df[col] - mean) / std

In [ ]:
# Count "high-sales outlier" orders where Sales_z > +2
if 'Sales_z' in df.columns:
    high_sales_outliers = df[df['Sales_z'] > 2]
    n_high_sales_outliers = len(high_sales_outliers)
else:
    n_high_sales_outliers = 0

print(f"\nNumber of high-sales outlier orders (Sales_z > +2): {n_high_sales_outliers}")

Number of high-sales outlier orders (Sales_z > +2): 247

In [ ]:
# Optionally: display top 10 high-sales orders
if n_high_sales_outliers > 0:
    print("\nTop high-sales outlier orders (by Sales_z):")
    display_cols = ['OrderID' if 'OrderID' in df.columns else 'Order Id','OrderDate','Region','Sales','Sales_z','Profit','ProfitMargin']
    display_cols = [c for c in display_cols if c in df.columns]
    print(high_sales_outliers.sort_values('Sales_z', ascending=False)[display_cols].head(10))

Top high-sales outlier orders (by Sales_z):
       Region      Sales    Sales_z     Profit  ProfitMargin
2697    South  22638.480  35.956549 -1811.0784     -0.080000
6826  Central  17499.950  27.711339  8399.9760      0.480000
8153     West  13999.960  22.095306  6719.9808      0.480000
2623     East  11199.968  17.602479  3919.9888      0.350000
4190     East  10499.970  16.479273  5039.9856      0.480000
9039  Central   9892.740  15.504920  4946.3700      0.500000
4098  Central   9449.950  14.794426  4630.4755      0.490000
4277     East   9099.930  14.232789  2365.9818      0.260000
8488    South   8749.950  13.671216  2799.9840      0.320000
6425     East   8399.976  13.109653  1119.9968      0.133333

In [ ]:
# --- 4. Binning (discretization)

In [ ]:
# Create SalesBin into 4 quartiles labeled Low, Medium, High, Very High
# Use qcut; drop NA Sales first if any
df_nonnull_sales = df[df['Sales'].notna()].copy()
labels = ['Low', 'Medium', 'High', 'Very High']
try:
    df_nonnull_sales['SalesBin'] = pd.qcut(df_nonnull_sales['Sales'], q=4, labels=labels)
except ValueError as e:
    # if qcut fails (e.g., too many identical values), fallback to cut with quantiles computed manually
    quantiles = df_nonnull_sales['Sales'].quantile([0, .25, .5, .75, 1.0]).values
    df_nonnull_sales['SalesBin'] = pd.cut(df_nonnull_sales['Sales'], bins=quantiles, labels=labels, include_lowest=True)

In [ ]:
# Compute average ProfitMargin for each Category × SalesBin
if 'Category' in df_nonnull_sales.columns:
    pivot_pm = pd.pivot_table(
        df_nonnull_sales,
        index='Category',
        columns='SalesBin',
        values='ProfitMargin',
        aggfunc='mean'
    )
    print("\nAverage ProfitMargin by Category × SalesBin (rows=Category, columns=SalesBin):")
    print(pivot_pm)
else:
    pivot_pm = None
    print("\nNo 'Category' column found in data — cannot compute pivot.")

Average ProfitMargin by Category × SalesBin (rows=Category, columns=SalesBin):
SalesBin              Low    Medium      High  Very High
Category
Furniture        0.068302  0.169013  0.017319  -0.003401
Office Supplies  0.020568  0.225236  0.213295   0.143491
Technology       0.168115  0.125657  0.167654   0.156947

/tmp/ipython-input-52152860.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_pm = pd.pivot_table(

In [ ]:
# Interpretation helper: show top categories within 'Very High' bin sorted by ProfitMargin
if pivot_pm is not None and 'Very High' in pivot_pm.columns:
    top_in_very_high = pivot_pm['Very High'].sort_values(ascending=False)
    print("\nCategories sorted by ProfitMargin within 'Very High' SalesBin:")
    print(top_in_very_high)

Categories sorted by ProfitMargin within 'Very High' SalesBin:
Category
Technology         0.156947
Office Supplies    0.143491
Furniture         -0.003401
Name: Very High, dtype: float64